language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "14"
   - "12"

before_install: npm i -g npm@6.14.12

before_script:
   - npm install -g grunt-cli
   - npm install -g mocha-phantomjs
